name: Commit Checker

# Run on push to any branch
on: [pull_request,push]

jobs:
  Commit_Checker:
    runs-on: [self-hosted]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: '${{ github.event.pull_request.base.ref }}'

    - name: Commit validation
      run: git checkout -q ${{ github.event.pull_request.head.ref }} | ./commit-msg ${{ github.event.pull_request.base.ref }}
      shell: bash
