name: Commit Checker

# Run on push to any branch
on: [pull_request,push]

jobs:
  Commit_Checker:
    runs-on: [self-hosted]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: '${{ github.event.pull_request.base.ref }}'

    - name: Commit validation
      env:
        BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
      run: git checkout -q $HEAD_BRANCH | ./commit-msg
      shell: bash
